### ISSUE TITLE
removed all capabilities and added not all "default" capabilities cause warning in test 5.3

### ISSUE THREAD

**Issue by immae1** [docker/docker-bench-security#207]
I have the following Docker-Compose file: 
```
version: '2'
volumes:
  db:
  db_templates:
  files:
  helpers:
  ssh-config:
services:
  mail:
    image: djfarrelly/maildev
    ports:
      - "127.0.0.1:1080:80"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
  redis:
    image: redis
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
  db:
    image: postgres
    command: -c fsync=off
    volumes:
      - db:/var/lib/postgresql/data
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - FOWNER
  db_templates:
    image: postgres
    command: -c fsync=off
    volumes:
      - db_templates:/var/lib/postgresql/data
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - FOWNER
  web:
    build: .
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
    volumes:
      - ./:/home/user/${COMPOSE_PROJECT_NAME}/
      - files:/home/user/files/
      - db:/db
      - helpers:/home/user/.pycharm_helpers/
      - ssh-config:/etc/ssh/
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8022:22"
    depends_on:
      - db
      - db_templates
      - redis
    command: bash -c "/home/user/${COMPOSE_PROJECT_NAME}/bin/helpers/run && sleep infinity"
  worker:
    build: .
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
    volumes:
      - ./:/home/user/${COMPOSE_PROJECT_NAME}/
      - files:/home/user/files/
      - db:/db
    depends_on:
      - db
      - db_templates
      - redis
    command:  bash -c "/home/user/${COMPOSE_PROJECT_NAME}/bin/helpers/run && su - user -c \"./manage.py supervisor\"" 
```
If i run the dockerbench testsuite i get the following warnings:

```
[WARN] 5.3  - Restrict Linux Kernel Capabilities within containers
[WARN]      * Capabilities added: CapAdd={[CHOWN DAC_OVERRIDE SETGID SETUID NET_BIND_SERVICE SYS_CHROOT]} to web_1
[WARN]      * Capabilities added: CapAdd={[CHOWN DAC_OVERRIDE SETGID SETUID NET_BIND_SERVICE SYS_CHROOT]} to  worker_1
[WARN]      * Capabilities added: CapAdd={[CHOWN DAC_OVERRIDE SETGID SETUID NET_BIND_SERVICE FOWNER]} to db_1
[WARN]      * Capabilities added: CapAdd={[CHOWN DAC_OVERRIDE SETGID SETUID NET_BIND_SERVICE FOWNER]} to db_templates_1
[WARN]      * Capabilities added: CapAdd={[NET_BIND_SERVICE CHOWN SETGID SETUID]} to redis_1
[WARN]      * Capabilities added: CapAdd={[NET_BIND_SERVICE]} mail_1
``` 

I think this behavior is wrong, because i run my containers with less capabilities than the default.
